ALT: Fix build of random.c
There was build failure since 5.10.119 caused by 'harmless' commit
imported from Ubuntu in 2020:

    CC      drivers/char/random.o
  drivers/char/random.c:232:9: error: unknown type name 'local_lock_t'
    232 |         local_lock_t lock;
	|         ^~~~~~~~~~~~

Fixes: e718bf9fd8b7 ("UBUNTU: SAUCE: Revert "radix-tree: Use local_lock for protection"")
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>